// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineCellar.Infrastructure.Persistence;

#nullable disable

namespace WineCellar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230331140306_AddedIsSpotlitToWinery")]
    partial class AddedIsSpotlitToWinery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WineCellar.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 6,
                            Name = "France"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 13,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 15,
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Grape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GrapeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Grapes", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.GrapeWine", b =>
                {
                    b.Property<int>("GrapeId")
                        .HasColumnType("int");

                    b.Property<int>("WineId")
                        .HasColumnType("int");

                    b.HasKey("GrapeId", "WineId");

                    b.HasIndex("WineId");

                    b.ToTable("GrapeWine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3543),
                            Name = "Salta"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3547),
                            Name = "Tucamán"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3548),
                            Name = "Catamarca"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3549),
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3549),
                            Name = "San Juan"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3550),
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3551),
                            Name = "Patagonia"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3552),
                            Name = "Western Australia"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3553),
                            Name = "South Australia"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3553),
                            Name = "New South Wales"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3554),
                            Name = "Victoria"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3555),
                            Name = "Tasmania"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3556),
                            Name = "Queensland"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3556),
                            Name = "Niederösterreich"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3557),
                            Name = "Burgenland"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3558),
                            Name = "Steiermark"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3558),
                            Name = "Wien"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 4,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3560),
                            Name = "Flanders"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 4,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3561),
                            Name = "Wallonia"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3562),
                            Name = "Central Valley"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3562),
                            Name = "Aconcagua"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3563),
                            Name = "South Region"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3564),
                            Name = "Coquimbo"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3564),
                            Name = "Atacama"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3565),
                            Name = "Austral Region"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3566),
                            Name = "Languadoc-Roussillon"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3566),
                            Name = "Rhône Valley"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3567),
                            Name = "Bordeaux"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3568),
                            Name = "Provence"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3568),
                            Name = "Loire Valley"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3569),
                            Name = "South-West"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3570),
                            Name = "Burgundy"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3571),
                            Name = "Champagne"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3572),
                            Name = "Alsace"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3573),
                            Name = "Beaujolais"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3573),
                            Name = "Corsica"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3574),
                            Name = "Ahr"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3575),
                            Name = "Mosel"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3576),
                            Name = "Nahe"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3577),
                            Name = "Pfalz"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3577),
                            Name = "Baden"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3611),
                            Name = "Mittelrhein"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3611),
                            Name = "Rheingan"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3612),
                            Name = "Rheinhessen"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3613),
                            Name = "Hessische Bergstrasse"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3614),
                            Name = "Würtemberg"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3614),
                            Name = "Franken"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3615),
                            Name = "Saale-Unstrut"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3616),
                            Name = "Sachsen"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3616),
                            Name = "Southern Greece"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3617),
                            Name = "Crete"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3618),
                            Name = "Central Greece"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3618),
                            Name = "Aegean Islands"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3619),
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3620),
                            Name = "Badacsony"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3620),
                            Name = "Balatonboglár"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3621),
                            Name = "Villány"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3622),
                            Name = "Szekszárd"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3622),
                            Name = "Balatonfüred-Csopak"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3623),
                            Name = "Mátra"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3626),
                            Name = "Tokaj"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3627),
                            Name = "Eger"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3628),
                            Name = "Etyek-Buda"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3628),
                            Name = "Pannonhalma"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3629),
                            Name = "Sopron"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3630),
                            Name = "Nagy-Somló"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3630),
                            Name = "Sicily"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3631),
                            Name = "Puglia"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3632),
                            Name = "Veneto"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3632),
                            Name = "Tuscany"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3633),
                            Name = "Emilia-Romagna"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3634),
                            Name = "Piedmont"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3634),
                            Name = "Abruzzo"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3635),
                            Name = "Lombardy"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3636),
                            Name = "Friuli-Venesia Giulia"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3636),
                            Name = "Abruzzo"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3637),
                            Name = "Sardegna"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3638),
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3638),
                            Name = "Umbria"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3639),
                            Name = "Northland"
                        },
                        new
                        {
                            Id = 82,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3640),
                            Name = "Waikato / Bay Of Plenty"
                        },
                        new
                        {
                            Id = 83,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3640),
                            Name = "Gisborne"
                        },
                        new
                        {
                            Id = 84,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3641),
                            Name = "Wairarapa"
                        },
                        new
                        {
                            Id = 85,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3642),
                            Name = "Marlborough"
                        },
                        new
                        {
                            Id = 86,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3642),
                            Name = "Caterbury and Waipara"
                        },
                        new
                        {
                            Id = 87,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3643),
                            Name = "Central Otago"
                        },
                        new
                        {
                            Id = 88,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3644),
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = 89,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3644),
                            Name = "Hawke's Bay"
                        },
                        new
                        {
                            Id = 90,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3645),
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = 91,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3646),
                            Name = "Vinho Verde"
                        },
                        new
                        {
                            Id = 92,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3646),
                            Name = "Dão"
                        },
                        new
                        {
                            Id = 93,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3647),
                            Name = "Bairrada"
                        },
                        new
                        {
                            Id = 94,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3648),
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 95,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3648),
                            Name = "Setúbal"
                        },
                        new
                        {
                            Id = 96,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3649),
                            Name = "Madeira"
                        },
                        new
                        {
                            Id = 97,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3650),
                            Name = "Algarve"
                        },
                        new
                        {
                            Id = 98,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3650),
                            Name = "Alentejo"
                        },
                        new
                        {
                            Id = 99,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3651),
                            Name = "Tejo"
                        },
                        new
                        {
                            Id = 100,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3652),
                            Name = "Beira Interior"
                        },
                        new
                        {
                            Id = 101,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3652),
                            Name = "Tavaro-Varosa"
                        },
                        new
                        {
                            Id = 102,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3653),
                            Name = "Douro Valley"
                        },
                        new
                        {
                            Id = 103,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3654),
                            Name = "Trás-os-Montes"
                        },
                        new
                        {
                            Id = 104,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3654),
                            Name = "Olifants River"
                        },
                        new
                        {
                            Id = 105,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3655),
                            Name = "Coastal Region"
                        },
                        new
                        {
                            Id = 106,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3656),
                            Name = "Breede River Valley"
                        },
                        new
                        {
                            Id = 107,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3688),
                            Name = "Northern Cape"
                        },
                        new
                        {
                            Id = 108,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3689),
                            Name = "Klein Karoo"
                        },
                        new
                        {
                            Id = 109,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3690),
                            Name = "Cape South Coast"
                        },
                        new
                        {
                            Id = 110,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3691),
                            Name = "Galicia"
                        },
                        new
                        {
                            Id = 111,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3691),
                            Name = "Pais Vasco"
                        },
                        new
                        {
                            Id = 112,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3692),
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 113,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3693),
                            Name = "Navarra"
                        },
                        new
                        {
                            Id = 114,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3694),
                            Name = "Aragon"
                        },
                        new
                        {
                            Id = 115,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3694),
                            Name = "Catalonia"
                        },
                        new
                        {
                            Id = 116,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3695),
                            Name = "Majorca"
                        },
                        new
                        {
                            Id = 117,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3696),
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 118,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3696),
                            Name = "Castilla-La Mancha"
                        },
                        new
                        {
                            Id = 119,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3697),
                            Name = "Castilla y León"
                        },
                        new
                        {
                            Id = 120,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3698),
                            Name = "Extremadura"
                        },
                        new
                        {
                            Id = 121,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3698),
                            Name = "Andalucía"
                        },
                        new
                        {
                            Id = 122,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3699),
                            Name = "Canary Islands"
                        },
                        new
                        {
                            Id = 123,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3700),
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 124,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3700),
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 125,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3701),
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = 126,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3702),
                            Name = "California"
                        },
                        new
                        {
                            Id = 127,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3702),
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 128,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3703),
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 129,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3704),
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = 130,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3704),
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 131,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3705),
                            Name = "New York"
                        },
                        new
                        {
                            Id = 132,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3706),
                            Name = "Midwest"
                        },
                        new
                        {
                            Id = 133,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3706),
                            Name = "Southeast"
                        },
                        new
                        {
                            Id = 134,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3707),
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = 135,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 31, 14, 3, 6, 669, DateTimeKind.Utc).AddTicks(3708),
                            Name = "Virginia"
                        });
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.UserWine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("WineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WineId");

                    b.ToTable("UserWines", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("WineType")
                        .HasColumnType("int");

                    b.Property<int>("WineryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WineryId");

                    b.ToTable("Wines", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsSpotlit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Wineries", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.GrapeWine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Grape", "Grape")
                        .WithMany("GrapeWines")
                        .HasForeignKey("GrapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineCellar.Domain.Entities.Wine", "Wine")
                        .WithMany("GrapeWines")
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grape");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Region", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.UserWine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Wine", "Wine")
                        .WithMany()
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("WineCellar.Domain.Entities.Winery", "Winery")
                        .WithMany("Wines")
                        .HasForeignKey("WineryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Winery");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Grape", b =>
                {
                    b.Navigation("GrapeWines");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.Navigation("GrapeWines");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.Navigation("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
