// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineCellar.Infrastructure.Persistence;

#nullable disable

namespace WineCellar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230628090746_RenameUserWineToBottle")]
    partial class RenameUserWineToBottle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WineCellar.Domain.Entities.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("BottleSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Vintage")
                        .HasColumnType("int");

                    b.Property<int>("WineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WineId");

                    b.ToTable("Bottles", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1498),
                            CreatedBy = "Seeding",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1502),
                            CreatedBy = "Seeding",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1504),
                            CreatedBy = "Seeding",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1506),
                            CreatedBy = "Seeding",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1508),
                            CreatedBy = "Seeding",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1510),
                            CreatedBy = "Seeding",
                            Name = "France"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1511),
                            CreatedBy = "Seeding",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1513),
                            CreatedBy = "Seeding",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1514),
                            CreatedBy = "Seeding",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1516),
                            CreatedBy = "Seeding",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1518),
                            CreatedBy = "Seeding",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1520),
                            CreatedBy = "Seeding",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1521),
                            CreatedBy = "Seeding",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1523),
                            CreatedBy = "Seeding",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(1524),
                            CreatedBy = "Seeding",
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Grape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GrapeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Grapes", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.GrapeWine", b =>
                {
                    b.Property<int>("GrapeId")
                        .HasColumnType("int");

                    b.Property<int>("WineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("GrapeId", "WineId");

                    b.HasIndex("WineId");

                    b.ToTable("GrapeWine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3088),
                            CreatedBy = "Seeding",
                            Name = "Salta"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3091),
                            CreatedBy = "Seeding",
                            Name = "Tucamán"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3093),
                            CreatedBy = "Seeding",
                            Name = "Catamarca"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3095),
                            CreatedBy = "Seeding",
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3097),
                            CreatedBy = "Seeding",
                            Name = "San Juan"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3099),
                            CreatedBy = "Seeding",
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3101),
                            CreatedBy = "Seeding",
                            Name = "Patagonia"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3102),
                            CreatedBy = "Seeding",
                            Name = "Western Australia"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3104),
                            CreatedBy = "Seeding",
                            Name = "South Australia"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3106),
                            CreatedBy = "Seeding",
                            Name = "New South Wales"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3107),
                            CreatedBy = "Seeding",
                            Name = "Victoria"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 2,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3109),
                            CreatedBy = "Seeding",
                            Name = "Tasmania"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 2,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3162),
                            CreatedBy = "Seeding",
                            Name = "Queensland"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 3,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3164),
                            CreatedBy = "Seeding",
                            Name = "Niederösterreich"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 3,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3166),
                            CreatedBy = "Seeding",
                            Name = "Burgenland"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 3,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3168),
                            CreatedBy = "Seeding",
                            Name = "Steiermark"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 3,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3170),
                            CreatedBy = "Seeding",
                            Name = "Wien"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 4,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3171),
                            CreatedBy = "Seeding",
                            Name = "Flanders"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 4,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3173),
                            CreatedBy = "Seeding",
                            Name = "Wallonia"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 5,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3175),
                            CreatedBy = "Seeding",
                            Name = "Central Valley"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 5,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3176),
                            CreatedBy = "Seeding",
                            Name = "Aconcagua"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 5,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3179),
                            CreatedBy = "Seeding",
                            Name = "South Region"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 5,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3181),
                            CreatedBy = "Seeding",
                            Name = "Coquimbo"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 5,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3182),
                            CreatedBy = "Seeding",
                            Name = "Atacama"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 5,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3184),
                            CreatedBy = "Seeding",
                            Name = "Austral Region"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3186),
                            CreatedBy = "Seeding",
                            Name = "Languadoc-Roussillon"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3187),
                            CreatedBy = "Seeding",
                            Name = "Rhône Valley"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3189),
                            CreatedBy = "Seeding",
                            Name = "Bordeaux"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3191),
                            CreatedBy = "Seeding",
                            Name = "Provence"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3192),
                            CreatedBy = "Seeding",
                            Name = "Loire Valley"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3194),
                            CreatedBy = "Seeding",
                            Name = "South-West"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3195),
                            CreatedBy = "Seeding",
                            Name = "Burgundy"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3197),
                            CreatedBy = "Seeding",
                            Name = "Champagne"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3199),
                            CreatedBy = "Seeding",
                            Name = "Alsace"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3200),
                            CreatedBy = "Seeding",
                            Name = "Beaujolais"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 6,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3202),
                            CreatedBy = "Seeding",
                            Name = "Corsica"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3203),
                            CreatedBy = "Seeding",
                            Name = "Ahr"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3205),
                            CreatedBy = "Seeding",
                            Name = "Mosel"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3207),
                            CreatedBy = "Seeding",
                            Name = "Nahe"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3208),
                            CreatedBy = "Seeding",
                            Name = "Pfalz"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3211),
                            CreatedBy = "Seeding",
                            Name = "Baden"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3212),
                            CreatedBy = "Seeding",
                            Name = "Mittelrhein"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3214),
                            CreatedBy = "Seeding",
                            Name = "Rheingan"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3216),
                            CreatedBy = "Seeding",
                            Name = "Rheinhessen"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3217),
                            CreatedBy = "Seeding",
                            Name = "Hessische Bergstrasse"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3219),
                            CreatedBy = "Seeding",
                            Name = "Würtemberg"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3220),
                            CreatedBy = "Seeding",
                            Name = "Franken"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3222),
                            CreatedBy = "Seeding",
                            Name = "Saale-Unstrut"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 7,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3224),
                            CreatedBy = "Seeding",
                            Name = "Sachsen"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 8,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3225),
                            CreatedBy = "Seeding",
                            Name = "Southern Greece"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 8,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3227),
                            CreatedBy = "Seeding",
                            Name = "Crete"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 8,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3228),
                            CreatedBy = "Seeding",
                            Name = "Central Greece"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 8,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3230),
                            CreatedBy = "Seeding",
                            Name = "Aegean Islands"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 8,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3231),
                            CreatedBy = "Seeding",
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3235),
                            CreatedBy = "Seeding",
                            Name = "Badacsony"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3236),
                            CreatedBy = "Seeding",
                            Name = "Balatonboglár"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3237),
                            CreatedBy = "Seeding",
                            Name = "Villány"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3239),
                            CreatedBy = "Seeding",
                            Name = "Szekszárd"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3241),
                            CreatedBy = "Seeding",
                            Name = "Balatonfüred-Csopak"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3242),
                            CreatedBy = "Seeding",
                            Name = "Mátra"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3247),
                            CreatedBy = "Seeding",
                            Name = "Tokaj"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3249),
                            CreatedBy = "Seeding",
                            Name = "Eger"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3250),
                            CreatedBy = "Seeding",
                            Name = "Etyek-Buda"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3252),
                            CreatedBy = "Seeding",
                            Name = "Pannonhalma"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3253),
                            CreatedBy = "Seeding",
                            Name = "Sopron"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 9,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3255),
                            CreatedBy = "Seeding",
                            Name = "Nagy-Somló"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3256),
                            CreatedBy = "Seeding",
                            Name = "Sicily"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3258),
                            CreatedBy = "Seeding",
                            Name = "Puglia"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3259),
                            CreatedBy = "Seeding",
                            Name = "Veneto"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3262),
                            CreatedBy = "Seeding",
                            Name = "Tuscany"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3264),
                            CreatedBy = "Seeding",
                            Name = "Emilia-Romagna"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3265),
                            CreatedBy = "Seeding",
                            Name = "Piedmont"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3267),
                            CreatedBy = "Seeding",
                            Name = "Abruzzo"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3269),
                            CreatedBy = "Seeding",
                            Name = "Lombardy"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3270),
                            CreatedBy = "Seeding",
                            Name = "Friuli-Venesia Giulia"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3272),
                            CreatedBy = "Seeding",
                            Name = "Sardegna"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3273),
                            CreatedBy = "Seeding",
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 10,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3275),
                            CreatedBy = "Seeding",
                            Name = "Umbria"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3276),
                            CreatedBy = "Seeding",
                            Name = "Northland"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3279),
                            CreatedBy = "Seeding",
                            Name = "Waikato / Bay Of Plenty"
                        },
                        new
                        {
                            Id = 82,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3281),
                            CreatedBy = "Seeding",
                            Name = "Gisborne"
                        },
                        new
                        {
                            Id = 83,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3282),
                            CreatedBy = "Seeding",
                            Name = "Wairarapa"
                        },
                        new
                        {
                            Id = 84,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3284),
                            CreatedBy = "Seeding",
                            Name = "Marlborough"
                        },
                        new
                        {
                            Id = 85,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3285),
                            CreatedBy = "Seeding",
                            Name = "Caterbury and Waipara"
                        },
                        new
                        {
                            Id = 86,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3287),
                            CreatedBy = "Seeding",
                            Name = "Central Otago"
                        },
                        new
                        {
                            Id = 87,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3288),
                            CreatedBy = "Seeding",
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = 88,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3290),
                            CreatedBy = "Seeding",
                            Name = "Hawke's Bay"
                        },
                        new
                        {
                            Id = 89,
                            CountryId = 11,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3291),
                            CreatedBy = "Seeding",
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = 90,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3293),
                            CreatedBy = "Seeding",
                            Name = "Vinho Verde"
                        },
                        new
                        {
                            Id = 91,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3294),
                            CreatedBy = "Seeding",
                            Name = "Dão"
                        },
                        new
                        {
                            Id = 92,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3295),
                            CreatedBy = "Seeding",
                            Name = "Bairrada"
                        },
                        new
                        {
                            Id = 93,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3297),
                            CreatedBy = "Seeding",
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 94,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3299),
                            CreatedBy = "Seeding",
                            Name = "Setúbal"
                        },
                        new
                        {
                            Id = 95,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3300),
                            CreatedBy = "Seeding",
                            Name = "Madeira"
                        },
                        new
                        {
                            Id = 96,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3302),
                            CreatedBy = "Seeding",
                            Name = "Algarve"
                        },
                        new
                        {
                            Id = 97,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3303),
                            CreatedBy = "Seeding",
                            Name = "Alentejo"
                        },
                        new
                        {
                            Id = 98,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3305),
                            CreatedBy = "Seeding",
                            Name = "Tejo"
                        },
                        new
                        {
                            Id = 99,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3306),
                            CreatedBy = "Seeding",
                            Name = "Beira Interior"
                        },
                        new
                        {
                            Id = 100,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3308),
                            CreatedBy = "Seeding",
                            Name = "Tavaro-Varosa"
                        },
                        new
                        {
                            Id = 101,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3309),
                            CreatedBy = "Seeding",
                            Name = "Douro Valley"
                        },
                        new
                        {
                            Id = 102,
                            CountryId = 12,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3311),
                            CreatedBy = "Seeding",
                            Name = "Trás-os-Montes"
                        },
                        new
                        {
                            Id = 103,
                            CountryId = 13,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3312),
                            CreatedBy = "Seeding",
                            Name = "Olifants River"
                        },
                        new
                        {
                            Id = 104,
                            CountryId = 13,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3314),
                            CreatedBy = "Seeding",
                            Name = "Coastal Region"
                        },
                        new
                        {
                            Id = 105,
                            CountryId = 13,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3315),
                            CreatedBy = "Seeding",
                            Name = "Breede River Valley"
                        },
                        new
                        {
                            Id = 106,
                            CountryId = 13,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3317),
                            CreatedBy = "Seeding",
                            Name = "Northern Cape"
                        },
                        new
                        {
                            Id = 107,
                            CountryId = 13,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3318),
                            CreatedBy = "Seeding",
                            Name = "Klein Karoo"
                        },
                        new
                        {
                            Id = 108,
                            CountryId = 13,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3320),
                            CreatedBy = "Seeding",
                            Name = "Cape South Coast"
                        },
                        new
                        {
                            Id = 109,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3321),
                            CreatedBy = "Seeding",
                            Name = "Galicia"
                        },
                        new
                        {
                            Id = 110,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3323),
                            CreatedBy = "Seeding",
                            Name = "Pais Vasco"
                        },
                        new
                        {
                            Id = 111,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3325),
                            CreatedBy = "Seeding",
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 112,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3326),
                            CreatedBy = "Seeding",
                            Name = "Navarra"
                        },
                        new
                        {
                            Id = 113,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3328),
                            CreatedBy = "Seeding",
                            Name = "Aragon"
                        },
                        new
                        {
                            Id = 114,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3329),
                            CreatedBy = "Seeding",
                            Name = "Catalonia"
                        },
                        new
                        {
                            Id = 115,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3331),
                            CreatedBy = "Seeding",
                            Name = "Majorca"
                        },
                        new
                        {
                            Id = 116,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3379),
                            CreatedBy = "Seeding",
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 117,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3381),
                            CreatedBy = "Seeding",
                            Name = "Castilla-La Mancha"
                        },
                        new
                        {
                            Id = 118,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3382),
                            CreatedBy = "Seeding",
                            Name = "Castilla y León"
                        },
                        new
                        {
                            Id = 119,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3384),
                            CreatedBy = "Seeding",
                            Name = "Extremadura"
                        },
                        new
                        {
                            Id = 120,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3385),
                            CreatedBy = "Seeding",
                            Name = "Andalucía"
                        },
                        new
                        {
                            Id = 121,
                            CountryId = 14,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3387),
                            CreatedBy = "Seeding",
                            Name = "Canary Islands"
                        },
                        new
                        {
                            Id = 122,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3389),
                            CreatedBy = "Seeding",
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 123,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3390),
                            CreatedBy = "Seeding",
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 124,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3392),
                            CreatedBy = "Seeding",
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = 125,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3393),
                            CreatedBy = "Seeding",
                            Name = "California"
                        },
                        new
                        {
                            Id = 126,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3395),
                            CreatedBy = "Seeding",
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 127,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3396),
                            CreatedBy = "Seeding",
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 128,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3398),
                            CreatedBy = "Seeding",
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = 129,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3399),
                            CreatedBy = "Seeding",
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 130,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3401),
                            CreatedBy = "Seeding",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 131,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3402),
                            CreatedBy = "Seeding",
                            Name = "Midwest"
                        },
                        new
                        {
                            Id = 132,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3404),
                            CreatedBy = "Seeding",
                            Name = "Southeast"
                        },
                        new
                        {
                            Id = 133,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3405),
                            CreatedBy = "Seeding",
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = 134,
                            CountryId = 15,
                            Created = new DateTime(2023, 6, 28, 9, 7, 46, 306, DateTimeKind.Utc).AddTicks(3407),
                            CreatedBy = "Seeding",
                            Name = "Virginia"
                        });
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RegionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("WineType")
                        .HasColumnType("int");

                    b.Property<int>("WineryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WineryId");

                    b.ToTable("Wines", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Wineries", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Bottle", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Wine", "Wine")
                        .WithMany()
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.GrapeWine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Grape", "Grape")
                        .WithMany("GrapeWines")
                        .HasForeignKey("GrapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineCellar.Domain.Entities.Wine", "Wine")
                        .WithMany("GrapeWines")
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grape");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Region", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineCellar.Domain.Entities.Winery", "Winery")
                        .WithMany("Wines")
                        .HasForeignKey("WineryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Winery");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Grape", b =>
                {
                    b.Navigation("GrapeWines");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.Navigation("GrapeWines");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.Navigation("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
