// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineCellar.Infrastructure.Persistence;

#nullable disable

namespace WineCellar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230330100650_AddedRegions")]
    partial class AddedRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WineCellar.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 6,
                            Name = "France"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 13,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 15,
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Grape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("GrapeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Grapes", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.GrapeWine", b =>
                {
                    b.Property<int>("GrapeId")
                        .HasColumnType("int");

                    b.Property<int>("WineId")
                        .HasColumnType("int");

                    b.HasKey("GrapeId", "WineId");

                    b.HasIndex("WineId");

                    b.ToTable("GrapeWine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3873),
                            Name = "Salta"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3877),
                            Name = "Tucamán"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3879),
                            Name = "Catamarca"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3880),
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3881),
                            Name = "San Juan"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3882),
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3883),
                            Name = "Patagonia"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3884),
                            Name = "Western Australia"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3884),
                            Name = "South Australia"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3885),
                            Name = "New South Wales"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3886),
                            Name = "Victoria"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3887),
                            Name = "Tasmania"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 2,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3888),
                            Name = "Queensland"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3888),
                            Name = "Niederösterreich"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3889),
                            Name = "Burgenland"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3891),
                            Name = "Steiermark"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 3,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3892),
                            Name = "Wien"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 4,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3892),
                            Name = "Flanders"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 4,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3893),
                            Name = "Wallonia"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3894),
                            Name = "Central Valley"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3894),
                            Name = "Aconcagua"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3895),
                            Name = "South Region"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3896),
                            Name = "Coquimbo"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3897),
                            Name = "Atacama"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 5,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3897),
                            Name = "Austral Region"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3898),
                            Name = "Languadoc-Roussillon"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3899),
                            Name = "Rhône Valley"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3900),
                            Name = "Bordeaux"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3900),
                            Name = "Provence"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3901),
                            Name = "Loire Valley"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3902),
                            Name = "South-West"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3940),
                            Name = "Burgundy"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3941),
                            Name = "Champagne"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3942),
                            Name = "Alsace"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3943),
                            Name = "Beaujolais"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 6,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3944),
                            Name = "Corsica"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3945),
                            Name = "Ahr"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3946),
                            Name = "Mosel"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3947),
                            Name = "Nahe"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3947),
                            Name = "Pfalz"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3948),
                            Name = "Baden"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3949),
                            Name = "Mittelrhein"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3950),
                            Name = "Rheingan"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3950),
                            Name = "Rheinhessen"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3951),
                            Name = "Hessische Bergstrasse"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3952),
                            Name = "Würtemberg"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3953),
                            Name = "Franken"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3953),
                            Name = "Saale-Unstrut"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 7,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3954),
                            Name = "Sachsen"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3955),
                            Name = "Southern Greece"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3956),
                            Name = "Crete"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3956),
                            Name = "Central Greece"
                        },
                        new
                        {
                            Id = 53,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3957),
                            Name = "Aegean Islands"
                        },
                        new
                        {
                            Id = 54,
                            CountryId = 8,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3958),
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 55,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3958),
                            Name = "Badacsony"
                        },
                        new
                        {
                            Id = 56,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3959),
                            Name = "Balatonboglár"
                        },
                        new
                        {
                            Id = 57,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3960),
                            Name = "Villány"
                        },
                        new
                        {
                            Id = 58,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3961),
                            Name = "Szekszárd"
                        },
                        new
                        {
                            Id = 59,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3961),
                            Name = "Balatonfüred-Csopak"
                        },
                        new
                        {
                            Id = 60,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3962),
                            Name = "Mátra"
                        },
                        new
                        {
                            Id = 61,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3963),
                            Name = "Tokaj"
                        },
                        new
                        {
                            Id = 62,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3965),
                            Name = "Eger"
                        },
                        new
                        {
                            Id = 63,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3965),
                            Name = "Etyek-Buda"
                        },
                        new
                        {
                            Id = 64,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3966),
                            Name = "Pannonhalma"
                        },
                        new
                        {
                            Id = 65,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3967),
                            Name = "Sopron"
                        },
                        new
                        {
                            Id = 67,
                            CountryId = 9,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3968),
                            Name = "Nagy-Somló"
                        },
                        new
                        {
                            Id = 68,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3968),
                            Name = "Sicily"
                        },
                        new
                        {
                            Id = 69,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3969),
                            Name = "Puglia"
                        },
                        new
                        {
                            Id = 70,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3970),
                            Name = "Veneto"
                        },
                        new
                        {
                            Id = 71,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3971),
                            Name = "Tuscany"
                        },
                        new
                        {
                            Id = 72,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3971),
                            Name = "Emilia-Romagna"
                        },
                        new
                        {
                            Id = 73,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3972),
                            Name = "Piedmont"
                        },
                        new
                        {
                            Id = 74,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3973),
                            Name = "Abruzzo"
                        },
                        new
                        {
                            Id = 75,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3974),
                            Name = "Lombardy"
                        },
                        new
                        {
                            Id = 76,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3974),
                            Name = "Friuli-Venesia Giulia"
                        },
                        new
                        {
                            Id = 77,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3975),
                            Name = "Abruzzo"
                        },
                        new
                        {
                            Id = 78,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3976),
                            Name = "Sardegna"
                        },
                        new
                        {
                            Id = 79,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3976),
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = 80,
                            CountryId = 10,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3977),
                            Name = "Umbria"
                        },
                        new
                        {
                            Id = 81,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3978),
                            Name = "Northland"
                        },
                        new
                        {
                            Id = 82,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3979),
                            Name = "Waikato / Bay Of Plenty"
                        },
                        new
                        {
                            Id = 83,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3979),
                            Name = "Gisborne"
                        },
                        new
                        {
                            Id = 84,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3980),
                            Name = "Wairarapa"
                        },
                        new
                        {
                            Id = 85,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3981),
                            Name = "Marlborough"
                        },
                        new
                        {
                            Id = 86,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3981),
                            Name = "Caterbury and Waipara"
                        },
                        new
                        {
                            Id = 87,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3982),
                            Name = "Central Otago"
                        },
                        new
                        {
                            Id = 88,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3983),
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = 89,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3984),
                            Name = "Hawke's Bay"
                        },
                        new
                        {
                            Id = 90,
                            CountryId = 11,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3984),
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = 91,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3985),
                            Name = "Vinho Verde"
                        },
                        new
                        {
                            Id = 92,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3987),
                            Name = "Dão"
                        },
                        new
                        {
                            Id = 93,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3987),
                            Name = "Bairrada"
                        },
                        new
                        {
                            Id = 94,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3988),
                            Name = "Lisboa"
                        },
                        new
                        {
                            Id = 95,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3989),
                            Name = "Setúbal"
                        },
                        new
                        {
                            Id = 96,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(3989),
                            Name = "Madeira"
                        },
                        new
                        {
                            Id = 97,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4026),
                            Name = "Algarve"
                        },
                        new
                        {
                            Id = 98,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4027),
                            Name = "Alentejo"
                        },
                        new
                        {
                            Id = 99,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4027),
                            Name = "Tejo"
                        },
                        new
                        {
                            Id = 100,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4028),
                            Name = "Beira Interior"
                        },
                        new
                        {
                            Id = 101,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4029),
                            Name = "Tavaro-Varosa"
                        },
                        new
                        {
                            Id = 102,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4030),
                            Name = "Douro Valley"
                        },
                        new
                        {
                            Id = 103,
                            CountryId = 12,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4030),
                            Name = "Trás-os-Montes"
                        },
                        new
                        {
                            Id = 104,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4031),
                            Name = "Olifants River"
                        },
                        new
                        {
                            Id = 105,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4032),
                            Name = "Coastal Region"
                        },
                        new
                        {
                            Id = 106,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4033),
                            Name = "Breede River Valley"
                        },
                        new
                        {
                            Id = 107,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4034),
                            Name = "Northern Cape"
                        },
                        new
                        {
                            Id = 108,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4034),
                            Name = "Klein Karoo"
                        },
                        new
                        {
                            Id = 109,
                            CountryId = 13,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4035),
                            Name = "Cape South Coast"
                        },
                        new
                        {
                            Id = 110,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4036),
                            Name = "Galicia"
                        },
                        new
                        {
                            Id = 111,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4037),
                            Name = "Pais Vasco"
                        },
                        new
                        {
                            Id = 112,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4037),
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 113,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4038),
                            Name = "Navarra"
                        },
                        new
                        {
                            Id = 114,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4039),
                            Name = "Aragon"
                        },
                        new
                        {
                            Id = 115,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4040),
                            Name = "Catalonia"
                        },
                        new
                        {
                            Id = 116,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4040),
                            Name = "Majorca"
                        },
                        new
                        {
                            Id = 117,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4041),
                            Name = "Valencia"
                        },
                        new
                        {
                            Id = 118,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4042),
                            Name = "Castilla-La Mancha"
                        },
                        new
                        {
                            Id = 119,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4042),
                            Name = "Castilla y León"
                        },
                        new
                        {
                            Id = 120,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4043),
                            Name = "Extremadura"
                        },
                        new
                        {
                            Id = 121,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4044),
                            Name = "Andalucía"
                        },
                        new
                        {
                            Id = 122,
                            CountryId = 14,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4045),
                            Name = "Canary Islands"
                        },
                        new
                        {
                            Id = 123,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4045),
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 124,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4046),
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 125,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4047),
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = 126,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4048),
                            Name = "California"
                        },
                        new
                        {
                            Id = 127,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4048),
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 128,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4049),
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 129,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4050),
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = 130,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4050),
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 131,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4051),
                            Name = "New York"
                        },
                        new
                        {
                            Id = 132,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4052),
                            Name = "Midwest"
                        },
                        new
                        {
                            Id = 133,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4053),
                            Name = "Southeast"
                        },
                        new
                        {
                            Id = 134,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4053),
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = 135,
                            CountryId = 15,
                            Created = new DateTime(2023, 3, 30, 10, 6, 49, 982, DateTimeKind.Utc).AddTicks(4054),
                            Name = "Virginia"
                        });
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.UserWine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("WineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WineId");

                    b.ToTable("UserWines", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("WineType")
                        .HasColumnType("int");

                    b.Property<int>("WineryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WineryId");

                    b.ToTable("Wines", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Wineries", (string)null);
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.GrapeWine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Grape", "Grape")
                        .WithMany("GrapeWines")
                        .HasForeignKey("GrapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineCellar.Domain.Entities.Wine", "Wine")
                        .WithMany("GrapeWines")
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grape");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Region", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.UserWine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Wine", "Wine")
                        .WithMany()
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("WineCellar.Domain.Entities.Winery", "Winery")
                        .WithMany("Wines")
                        .HasForeignKey("WineryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Winery");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.HasOne("WineCellar.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Grape", b =>
                {
                    b.Navigation("GrapeWines");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Wine", b =>
                {
                    b.Navigation("GrapeWines");
                });

            modelBuilder.Entity("WineCellar.Domain.Entities.Winery", b =>
                {
                    b.Navigation("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
